class AzAnimator{
	constructor(cfg={}){const t=this;
		t.cfg=Object.assign({
			adk: 'animation-duration',
			bvk: 'backface-visibility',
			atfk: 'animation-timing-function',
			tok: 'transform-origin',
			styleId: 'az_anim_style',
			extraCSS: ':root{--dur:1s;--delay:1s;--repeat:1}.az_anim,.az_anim_hov{animation-iteration-count:infinite;animation-duration:var(--dur);animation-fill-mode:both}.infinite{animation-iteration-count:infinite}.az_anim_paused{animation-play-state:paused}@property --angle{syntax:"<angle>";inherits:false;initial-value:0deg}',
			animList: [
				["blink_txt","50%{color:transparent}"],
				["blink_bg","50%{background:transparent}"],
				["blink_b_shadow","0%{box-shadow:none} 100%{box-shadow:0 0 999px 1px}"],
				["blink_brdr_r","50%{border-right:none}"],
				["cube_rotate","0%{transform:rotateY(0deg) rotateX(35deg)  rotateY(35deg)} 100%{transform:rotateY(360deg) rotateX(35deg)  rotateY(35deg)}"],
				["bounce","0%,20%,53%,to{animation-timing-function:cubic-bezier(.215,.61,.355,1);transform:translateZ(0)}40%,43%{animation-timing-function:cubic-bezier(.755,.05,.855,.06);transform:translate3d(0,-30px,0) scaleY(1.1)}70%{animation-timing-function:cubic-bezier(.755,.05,.855,.06);transform:translate3d(0,-15px,0) scaleY(1.05)}80%{transition-timing-function:cubic-bezier(.215,.61,.355,1);transform:translateZ(0) scaleY(.95)}90%{transform:translate3d(0,-4px,0) scaleY(1.02)}"],
				["flash","0%,50%,to{opacity:1}25%,75%{opacity:0}"],
				["pulse","0%{scale:1}50%{scale:1.01}100%{scale:1}"],
				["rubberBand","0%{transform:scaleX(1)}30%{transform:scale3d(1.25,.75,1)}40%{transform:scale3d(.75,1.25,1)}50%{transform:scale3d(1.15,.85,1)}65%{transform:scale3d(.95,1.05,1)}75%{transform:scale3d(1.05,.95,1)}to{transform:scaleX(1)}"],
				["shakeX","0%,to{transform:translateZ(0)}10%,30%,50%,70%,90%{transform:translate3d(-10px,0,0)}20%,40%,60%,80%{transform:translate3d(10px,0,0)}"],
				["shakeY","0%,to{transform:translateZ(0)}10%,30%,50%,70%,90%{transform:translate3d(0,-10px,0)}20%,40%,60%,80%{transform:translate3d(0,10px,0)}"],
				["headShake","0%{transform:translateX(0)}6.5%{transform:translateX(-6px) rotateY(-9deg)}18.5%{transform:translateX(5px) rotateY(7deg)}31.5%{transform:translateX(-3px) rotateY(-5deg)}43.5%{transform:translateX(2px) rotateY(3deg)}50%{transform:translateX(0)}"],
				["swing","20%{transform:rotate(15deg)}40%{transform:rotate(-10deg)}60%{transform:rotate(5deg)}80%{transform:rotate(-5deg)}to{transform:rotate(0deg)}"],
				["tada","0%{transform:scaleX(1)}10%,20%{transform:scale3d(.9,.9,.9) rotate(-3deg)}30%,50%,70%,90%{transform:scale3d(1.1,1.1,1.1) rotate(3deg)}40%,60%,80%{transform:scale3d(1.1,1.1,1.1) rotate(-3deg)}to{transform:scaleX(1)}"],
				["wobble","0%{transform:translateZ(0)}15%{transform:translate3d(-25%,0,0) rotate(-5deg)}30%{transform:translate3d(20%,0,0) rotate(3deg)}45%{transform:translate3d(-15%,0,0) rotate(-3deg)}60%{transform:translate3d(10%,0,0) rotate(2deg)}75%{transform:translate3d(-5%,0,0) rotate(-1deg)}to{transform:translateZ(0)}"],
				["jello","0%,11.1%,to{transform:translateZ(0)}22.2%{transform:skewX(-12.5deg) skewY(-12.5deg)}33.3%{transform:skewX(6.25deg) skewY(6.25deg)}44.4%{transform:skewX(-3.125deg) skewY(-3.125deg)}55.5%{transform:skewX(1.5625deg) skewY(1.5625deg)}66.6%{transform:skewX(-.78125deg) skewY(-.78125deg)}77.7%{transform:skewX(.390625deg) skewY(.390625deg)}88.8%{transform:skewX(-.1953125deg) skewY(-.1953125deg)}"],
				["backInDown","0%{transform:translateY(-1200px) scale(.7);opacity:.7}80%{transform:translateY(0) scale(.7);opacity:.7}to{transform:scale(1);opacity:1}"],
				["backInLeft","0%{transform:translateX(-2000px) scale(.7);opacity:.7}80%{transform:translateX(0) scale(.7);opacity:.7}to{transform:scale(1);opacity:1}"],
				["backInRight","0%{transform:translateX(2000px) scale(.7);opacity:.7}80%{transform:translateX(0) scale(.7);opacity:.7}to{transform:scale(1);opacity:1}"],
				["backInUp","0%{transform:translateY(1200px) scale(.7);opacity:.7}80%{transform:translateY(0) scale(.7);opacity:.7}to{transform:scale(1);opacity:1}"],
				["backOutDown","0%{transform:scale(1);opacity:1}20%{transform:translateY(0) scale(.7);opacity:.7}to{transform:translateY(700px) scale(.7);opacity:.7}"],
				["backOutLeft","0%{transform:scale(1);opacity:1}20%{transform:translateX(0) scale(.7);opacity:.7}to{transform:translateX(-2000px) scale(.7);opacity:.7}"],
				["backOutRight","0%{transform:scale(1);opacity:1}20%{transform:translateX(0) scale(.7);opacity:.7}to{transform:translateX(2000px) scale(.7);opacity:.7}"],
				["backOutUp","0%{transform:scale(1);opacity:1}20%{transform:translateY(0) scale(.7);opacity:.7}to{transform:translateY(-700px) scale(.7);opacity:.7}"],
				["bounceIn","0%,20%,40%,60%,80%,to{animation-timing-function:cubic-bezier(.215,.61,.355,1)}0%{opacity:0;transform:scale3d(.3,.3,.3)}20%{transform:scale3d(1.1,1.1,1.1)}40%{transform:scale3d(.9,.9,.9)}60%{opacity:1;transform:scale3d(1.03,1.03,1.03)}80%{transform:scale3d(.97,.97,.97)}to{opacity:1;transform:scaleX(1)}"],
				["bounceInDown","0%,60%,75%,90%,to{animation-timing-function:cubic-bezier(.215,.61,.355,1)}0%{opacity:0;transform:translate3d(0,-3000px,0) scaleY(3)}60%{opacity:1;transform:translate3d(0,25px,0) scaleY(.9)}75%{transform:translate3d(0,-10px,0) scaleY(.95)}90%{transform:translate3d(0,5px,0) scaleY(.985)}to{transform:translateZ(0)}"],
				["bounceInLeft","0%,60%,75%,90%,to{animation-timing-function:cubic-bezier(.215,.61,.355,1)}0%{opacity:0;transform:translate3d(-3000px,0,0) scaleX(3)}60%{opacity:1;transform:translate3d(25px,0,0) scaleX(1)}75%{transform:translate3d(-10px,0,0) scaleX(.98)}90%{transform:translate3d(5px,0,0) scaleX(.995)}to{transform:translateZ(0)}"],
				["bounceInRight","0%,60%,75%,90%,to{animation-timing-function:cubic-bezier(.215,.61,.355,1)}0%{opacity:0;transform:translate3d(3000px,0,0) scaleX(3)}60%{opacity:1;transform:translate3d(-25px,0,0) scaleX(1)}75%{transform:translate3d(10px,0,0) scaleX(.98)}90%{transform:translate3d(-5px,0,0) scaleX(.995)}to{transform:translateZ(0)}"],
				["bounceInUp","0%,60%,75%,90%,to{animation-timing-function:cubic-bezier(.215,.61,.355,1)}0%{opacity:0;transform:translate3d(0,3000px,0) scaleY(5)}60%{opacity:1;transform:translate3d(0,-20px,0) scaleY(.9)}75%{transform:translate3d(0,10px,0) scaleY(.95)}90%{transform:translate3d(0,-5px,0) scaleY(.985)}to{transform:translateZ(0)}"],
				["bounceOut","20%{transform:scale3d(.9,.9,.9)}50%,55%{opacity:1;transform:scale3d(1.1,1.1,1.1)}to{opacity:0;transform:scale3d(.3,.3,.3)}"],
				["bounceOutDown","20%{transform:translate3d(0,10px,0) scaleY(.985)}40%,45%{opacity:1;transform:translate3d(0,-20px,0) scaleY(.9)}to{opacity:0;transform:translate3d(0,2000px,0) scaleY(3)}"],
				["bounceOutLeft","20%{opacity:1;transform:translate3d(20px,0,0) scaleX(.9)}to{opacity:0;transform:translate3d(-2000px,0,0) scaleX(2)}"],
				["bounceOutRight","20%{opacity:1;transform:translate3d(-20px,0,0) scaleX(.9)}to{opacity:0;transform:translate3d(2000px,0,0) scaleX(2)}"],
				["bounceOutUp","20%{transform:translate3d(0,-10px,0) scaleY(.985)}40%,45%{opacity:1;transform:translate3d(0,20px,0) scaleY(.9)}to{opacity:0;transform:translate3d(0,-2000px,0) scaleY(3)}"],
				["heartBeat","0%{transform:scale(1)}14%{transform:scale(1.3)}28%{transform:scale(1)}42%{transform:scale(1.3)}70%{transform:scale(1)}"],
				["beatFade","0%,to{opacity:.4;transform:scale(1)}50%{opacity:1;transform:scale(1.12)}"],
				["fadeIn","0%{opacity:0}to{opacity:1}"],
				["fadeInDown","0%{opacity:0;transform:translate3d(0,-100%,0)}to{opacity:1;transform:translateZ(0)}"],
				["fadeInDownBig","0%{opacity:0;transform:translate3d(0,-2000px,0)}to{opacity:1;transform:translateZ(0)}"],
				["fadeInLeft","0%{opacity:0;transform:translate3d(-100%,0,0)}to{opacity:1;transform:translateZ(0)}"],
				["fadeInLeftBig","0%{opacity:0;transform:translate3d(-2000px,0,0)}to{opacity:1;transform:translateZ(0)}"],
				["fadeInRight","0%{opacity:0;transform:translate3d(100%,0,0)}to{opacity:1;transform:translateZ(0)}"],
				["fadeInRightBig","0%{opacity:0;transform:translate3d(2000px,0,0)}to{opacity:1;transform:translateZ(0)}"],
				["fadeInUp","0%{opacity:0;transform:translate3d(0,100%,0)}to{opacity:1;transform:translateZ(0)}"],
				["fadeInUpBig","0%{opacity:0;transform:translate3d(0,2000px,0)}to{opacity:1;transform:translateZ(0)}"],
				["fadeInTopLeft","0%{opacity:0;transform:translate3d(-100%,-100%,0)}to{opacity:1;transform:translateZ(0)}"],
				["fadeInTopRight","0%{opacity:0;transform:translate3d(100%,-100%,0)}to{opacity:1;transform:translateZ(0)}"],
				["fadeInBottomLeft","0%{opacity:0;transform:translate3d(-100%,100%,0)}to{opacity:1;transform:translateZ(0)}"],
				["fadeInBottomRight","0%{opacity:0;transform:translate3d(100%,100%,0)}to{opacity:1;transform:translateZ(0)}"],
				["fadeOut","0%{opacity:1}to{opacity:0}"],
				["fadeOutDown","0%{opacity:1}to{opacity:0;transform:translate3d(0,100%,0)}"],
				["fadeOutDownBig","0%{opacity:1}to{opacity:0;transform:translate3d(0,2000px,0)}"],
				["fadeOutLeft","0%{opacity:1}to{opacity:0;transform:translate3d(-100%,0,0)}"],
				["fadeOutLeftBig","0%{opacity:1}to{opacity:0;transform:translate3d(-2000px,0,0)}"],
				["fadeOutRight","0%{opacity:1}to{opacity:0;transform:translate3d(100%,0,0)}"],
				["fadeOutRightBig","0%{opacity:1}to{opacity:0;transform:translate3d(2000px,0,0)}"],
				["fadeOutUp","0%{opacity:1}to{opacity:0;transform:translate3d(0,-100%,0)}"],
				["fadeOutUpBig","0%{opacity:1}to{opacity:0;transform:translate3d(0,-2000px,0)}"],
				["fadeOutTopLeft","0%{opacity:1;transform:translateZ(0)}to{opacity:0;transform:translate3d(-100%,-100%,0)}"],
				["fadeOutTopRight","0%{opacity:1;transform:translateZ(0)}to{opacity:0;transform:translate3d(100%,-100%,0)}"],
				["fadeOutBottomRight","0%{opacity:1;transform:translateZ(0)}to{opacity:0;transform:translate3d(100%,100%,0)}"],
				["fadeOutBottomLeft","0%{opacity:1;transform:translateZ(0)}to{opacity:0;transform:translate3d(-100%,100%,0)}"],
				["flip","0%{transform:perspective(400px) scaleX(1) translateZ(0) rotateY(-1turn);animation-timing-function:ease-out}40%{transform:perspective(400px) scaleX(1) translateZ(150px) rotateY(-190deg);animation-timing-function:ease-out}50%{transform:perspective(400px) scaleX(1) translateZ(150px) rotateY(-170deg);animation-timing-function:ease-in}80%{transform:perspective(400px) scale3d(.95,.95,.95) translateZ(0) rotateY(0deg);animation-timing-function:ease-in}to{transform:perspective(400px) scaleX(1) translateZ(0) rotateY(0deg);animation-timing-function:ease-in}"],
				["flipInX","0%{transform:perspective(400px) rotateX(90deg);animation-timing-function:ease-in;opacity:0}40%{transform:perspective(400px) rotateX(-20deg);animation-timing-function:ease-in}60%{transform:perspective(400px) rotateX(10deg);opacity:1}80%{transform:perspective(400px) rotateX(-5deg)}to{transform:perspective(400px)}"],
				["flipInY","0%{transform:perspective(400px) rotateY(90deg);animation-timing-function:ease-in;opacity:0}40%{transform:perspective(400px) rotateY(-20deg);animation-timing-function:ease-in}60%{transform:perspective(400px) rotateY(10deg);opacity:1}80%{transform:perspective(400px) rotateY(-5deg)}to{transform:perspective(400px)}"],
				["flipOutX","0%{transform:perspective(400px)}30%{transform:perspective(400px) rotateX(-20deg);opacity:1}to{transform:perspective(400px) rotateX(90deg);opacity:0}"],
				["flipOutY","0%{transform:perspective(400px)}30%{transform:perspective(400px) rotateY(-15deg);opacity:1}to{transform:perspective(400px) rotateY(90deg);opacity:0}"],
				["lightSpeedInRight","0%{transform:translate3d(100%,0,0) skewX(-30deg);opacity:0}60%{transform:skewX(20deg);opacity:1}80%{transform:skewX(-5deg)}to{transform:translateZ(0)}"],
				["lightSpeedInLeft","0%{transform:translate3d(-100%,0,0) skewX(30deg);opacity:0}60%{transform:skewX(-20deg);opacity:1}80%{transform:skewX(5deg)}to{transform:translateZ(0)}"],
				["lightSpeedOutRight","0%{opacity:1}to{transform:translate3d(100%,0,0) skewX(30deg);opacity:0}"],
				["lightSpeedOutLeft","0%{opacity:1}to{transform:translate3d(-100%,0,0) skewX(-30deg);opacity:0}"],
				["rotateIn","0%{transform:rotate(-200deg);opacity:0}to{transform:translateZ(0);opacity:1}"],
				["rotateInDownLeft","0%{transform:rotate(-45deg);opacity:0}to{transform:translateZ(0);opacity:1}"],
				["rotateInDownRight","0%{transform:rotate(45deg);opacity:0}to{transform:translateZ(0);opacity:1}"],
				["rotateInUpLeft","0%{transform:rotate(45deg);opacity:0}to{transform:translateZ(0);opacity:1}"],
				["rotateInUpRight","0%{transform:rotate(-90deg);opacity:0}to{transform:translateZ(0);opacity:1}"],
				["rotateOut","0%{opacity:1}to{transform:rotate(200deg);opacity:0}"],
				["rotateOutDownLeft","0%{opacity:1}to{transform:rotate(45deg);opacity:0}"],
				["rotateOutDownRight","0%{opacity:1}to{transform:rotate(-45deg);opacity:0}"],
				["rotateOutUpLeft","0%{opacity:1}to{transform:rotate(-45deg);opacity:0}"],
				["rotateOutUpRight","0%{opacity:1}to{transform:rotate(90deg);opacity:0}"],
				["hinge","0%{animation-timing-function:ease-in-out}20%,60%{transform:rotate(80deg);animation-timing-function:ease-in-out}40%,80%{transform:rotate(60deg);animation-timing-function:ease-in-out;opacity:1}to{transform:translate3d(0,700px,0);opacity:0}"],
				["jackInTheBox","0%{opacity:0;transform:scale(.1) rotate(30deg);transform-origin:center bottom}50%{transform:rotate(-10deg)}70%{transform:rotate(3deg)}to{opacity:1;transform:scale(1)}"],
				["rollIn","0%{opacity:0;transform:translate3d(-100%,0,0) rotate(-120deg)}to{opacity:1;transform:translateZ(0)}"],
				["rollOut","0%{opacity:1}to{opacity:0;transform:translate3d(100%,0,0) rotate(120deg)}"],
				["zoomIn","0%{opacity:0;transform:scale3d(.3,.3,.3)}50%{opacity:1}"],
				["zoomInDown","0%{opacity:0;transform:scale3d(.1,.1,.1) translate3d(0,-1000px,0);animation-timing-function:cubic-bezier(.55,.055,.675,.19)}60%{opacity:1;transform:scale3d(.475,.475,.475) translate3d(0,60px,0);animation-timing-function:cubic-bezier(.175,.885,.32,1)}"],
				["zoomInLeft","0%{opacity:0;transform:scale3d(.1,.1,.1) translate3d(-1000px,0,0);animation-timing-function:cubic-bezier(.55,.055,.675,.19)}60%{opacity:1;transform:scale3d(.475,.475,.475) translate3d(10px,0,0);animation-timing-function:cubic-bezier(.175,.885,.32,1)}"],
				["zoomInRight","0%{opacity:0;transform:scale3d(.1,.1,.1) translate3d(1000px,0,0);animation-timing-function:cubic-bezier(.55,.055,.675,.19)}60%{opacity:1;transform:scale3d(.475,.475,.475) translate3d(-10px,0,0);animation-timing-function:cubic-bezier(.175,.885,.32,1)}"],
				["zoomInUp","0%{opacity:0;transform:scale3d(.1,.1,.1) translate3d(0,1000px,0);animation-timing-function:cubic-bezier(.55,.055,.675,.19)}60%{opacity:1;transform:scale3d(.475,.475,.475) translate3d(0,-60px,0);animation-timing-function:cubic-bezier(.175,.885,.32,1)}"],
				["zoomOut","0%{opacity:1}50%{opacity:0;transform:scale3d(.3,.3,.3)}to{opacity:0}"],
				["zoomOutDown","40%{opacity:1;transform:scale3d(.475,.475,.475) translate3d(0,-60px,0);animation-timing-function:cubic-bezier(.55,.055,.675,.19)}to{opacity:0;transform:scale3d(.1,.1,.1) translate3d(0,2000px,0);animation-timing-function:cubic-bezier(.175,.885,.32,1)}"],
				["zoomOutLeft","40%{opacity:1;transform:scale3d(.475,.475,.475) translate3d(42px,0,0)}to{opacity:0;transform:scale(.1) translate3d(-2000px,0,0)}"],
				["zoomOutRight","40%{opacity:1;transform:scale3d(.475,.475,.475) translate3d(-42px,0,0)}to{opacity:0;transform:scale(.1) translate3d(2000px,0,0)}"],
				["zoomOutUp","40%{opacity:1;transform:scale3d(.475,.475,.475) translate3d(0,60px,0);animation-timing-function:cubic-bezier(.55,.055,.675,.19)}to{opacity:0;transform:scale3d(.1,.1,.1) translate3d(0,-2000px,0);animation-timing-function:cubic-bezier(.175,.885,.32,1)}"],
				["slideInDown","0%{transform:translate3d(0,-100%,0);visibility:visible}to{transform:translateZ(0)}"],
				["slideInLeft","0%{transform:translate3d(-100%,0,0);visibility:visible}to{transform:translateZ(0)}"],
				["slideInRight","0%{transform:translate3d(100%,0,0);visibility:visible}to{transform:translateZ(0)}"],
				["slideInUp","0%{transform:translate3d(0,100%,0);visibility:visible}to{transform:translateZ(0)}"],
				["slideOutDown","0%{transform:translateZ(0)}to{visibility:hidden;transform:translate3d(0,100%,0)}"],
				["slideOutLeft","0%{transform:translateZ(0)}to{visibility:hidden;transform:translate3d(-100%,0,0)}"],
				["slideOutRight","0%{transform:translateZ(0)}to{visibility:hidden;transform:translate3d(100%,0,0)}"],
				["slideOutUp","0%{transform:translateZ(0)}to{visibility:hidden;transform:translate3d(0,-100%,0)}"],
				["slideThroughLeft","0%{left:-75%}to{left:125%}"],
				["slideThroughRight","0%{right:-75%}to{right:125%}"],
				["slideThroughUp","0%{bottom:-75%}to{bottom:125%}"],
				["slideThroughDown","0%{top:-75%}to{top:125%}"],
				["scaleIn","0%{transform:scale(0.3);opacity:0.2}80%{transform:scale(1);opacity:1}"],
				["gradientShift","0%{background-position-x:0%;background-position-y:20%}50%{background-position-x:150%;background-position-y:100%}100%{background-position-x:0%;background-position-y:20%}"],
				["fadeEffect","from{opacity:0}to{opacity:1}"],
				["spinConicGrad","from{--angle:0deg}to{--angle:360deg}"],
				["spin","from{transform:rotate(0deg)}to{transform:rotate(360deg)}"],
				["loadingDots","0%{transform:scale(1.5) rotate(42deg);color:transparent}50%{transform:scale(1) rotate(0deg);color:red}100%{transform:scale(1.5) rotate(42deg);color:green}"],
			]
		},cfg);t.adk=t.cfg.adk;t.bvk=t.cfg.bvk;t.atfk=t.cfg.atfk;t.tok=t.cfg.tok;t.extraCSS=t.cfg.extraCSS;t.init()
	}
	init(){var ents=this.buildEnts(),css=this.generateCSS(ents),keyframesCSS=this.generateAnimCSS(this.cfg.animList),aS=crEl('style');aS.id=this.cfg.styleId;aS.textContent=css+keyframesCSS+this.cfg.extraCSS;doc.head.appendChild(aS);this.applyDynamicProps()}
	buildEnts(){var o1=['blink_txt','blink_bg','blink_b_shadow','cube_rotate','blink_brdr_r','beatFade',"fadeOut","fadeOutDown","fadeOutDownBig","fadeOutLeft","fadeOutLeftBig","fadeOutRight","fadeOutRightBig","fadeOutUp","fadeOutUpBig","fadeOutTopLeft","fadeOutTopRight","fadeOutBottomRight","fadeOutBottomLeft","flipInX","flipInY","flash","pulse","rubberBand","shakeX","shakeY","headShake","swing","tada","wobble","jello","backInDown","backInLeft","backInRight","backInUp","backOutDown","backOutLeft","backOutRight","backOutUp","bounceIn","bounceInDown","bounceInLeft","bounceInRight","bounceInUp","bounceOutDown","bounceOutLeft","bounceOutRight","bounceOutUp","fadeIn","fadeInDown","fadeInDownBig","fadeInLeft","fadeInLeftBig","fadeInRight","fadeInRightBig","fadeInUp","fadeInUpBig","fadeInTopLeft","fadeInTopRight","fadeInBottomLeft","fadeInBottomRight","rotateOutUpLeft","rotateOutUpRight","bounce","jackInTheBox","rollIn","rollOut","zoomIn","zoomInDown","zoomInLeft","zoomInRight","zoomInUp","zoomOut","zoomOutDown","zoomOutLeft","zoomOutRight","zoomOutUp","slideInDown","slideInLeft","slideInRight","slideInUp","slideOutDown","slideOutLeft","slideOutRight","slideOutUp","slideThroughLeft","slideThroughRight","slideThroughUp","slideThroughDown","scaleIn","gradientShift","fadeEffect","spin","spinBg"].reduce((obj,animationName)=>{obj[animationName]={animationName};return obj},{}),o2=Object.fromEntries(Object.entries({flip:{bvk:"visible"},flipOutY:{bvk:"visible!important",adk:"calc(var(--dur)*0.75)"},flipOutX:{bvk:"visible!important",adk:"calc(var(--dur)*0.75)"},heartBeat:{atfk:"ease-in-out",adk:"calc(var(--dur)*1.3)"},bounceOut:{adk:"calc(var(--dur)*0.75)"},hinge:{tok:"top left",adk:"calc(var(--dur)*2)"},lightSpeedInRight:{atfk:"ease-out"},lightSpeedInLeft:{atfk:"ease-out"},lightSpeedOutRight:{atfk:"ease-in"},lightSpeedOutLeft:{atfk:"ease-in"},rotateIn:{tok:"center"},rotateInDownLeft:{tok:"left bottom"},rotateInDownRight:{tok:"right bottom"},rotateInUpLeft:{tok:"left bottom"},rotateInUpRight:{tok:"right bottom"},rotateOut:{tok:"center"},rotateOutDownLeft:{tok:"left bottom"},rotateOutDownRight:{tok:"right bottom"}}).map(([name,props])=>[name,{...props,animationName:name}]));return Object.entries({...o1,...o2});}
	generateCSS(ents){return ents.map(([name,props])=>{var rules=Object.entries(props).map(([prop,value])=>{if (prop === 'animationName') return `animation-name:${value};`;return `--${prop}:${value};`;}).join(' ');return `.az_anim_hov.${name}:hover{ ${rules} }\n.${name}:not(.az_anim_hov){ ${rules} }`;}).join('\n');}
	generateAnimCSS(animList){return animList.map(([name,frames])=>`@keyframes ${name}{ ${frames} }`).join('')}
	applyDynamicProps(){findEls('[class*="delay_"]').forEach(el=>{el.classList.forEach(cls=>{var m=cls.match(/^delay_(\d+(\.\d+)?)$/);if(m)el.style.setProperty('animation-delay',`calc(var(--delay)*${parseFloat(m[1])})`);});});findEls('[class*="repeat_"]').forEach(el=>{el.classList.forEach(cls=>{var m=cls.match(/^repeat_(\d+(\.\d+)?)$/);if(m) el.style.setProperty('animation-iteration-count',`calc(var(--repeat)*${parseFloat(m[1])})`);});});findEls('[class*="dur_"],[class*="speed_"]').forEach(el=>{el.classList.forEach(cls=>{var m=cls.match(/^(dur|speed)_(\d+(\.\d+)?)$/);if(m) el.style.setProperty(this.adk,`calc(var(--dur)*${parseFloat(m[2])})`);});});}
}
